const translationsEn = {
  // persons
  Национальность: "Nationality",
  "Место Рождения": "Place of Birth",
  "Родной Город": "Native city",
  Отец: "Father",
  Мать: "Mother",
  Специальность: "Speciality",
  Ассассин: "Assassin",
  Закрыть: "Close",
  Подробнее: "More",
  //
  "Альтаир ибн Ла-Ахад": "Altaïr Ibn-La'Ahad",
  Сарацин: "Saracen",
  Масиаф: "Masyaf",
  "Умар ибн Ла-Ахад": "Umar ibn La-Ahad",
  Мод: "Mod",
  //
  "Эцио Аудиторе Да Фиренце": "Ezio Auditore da Firenze",
  Италианец: "Italian",
  "Флоренция, Италия": "Florence, Italy",
  Флоренция: "Florence",
  "Джованни Аудиторе": "Giovanni Auditore",
  "Мария Аудиторе": "Maria Auditore",
  //
  "Коннор Кенуей": "Connor Kenway",
  Американец: "American",
  Ганадазедон: "Ganadasedon",
  "Хэйтем Кенуэй": "Hatem Kenway",
  Гадзидзио: "Gadjidzio",
  //
  "Эдвард Кенуей": "Edward Kenway",
  Англичанин: "Englishman",
  "Королевство Англии": "Kingdom of England",
  "Суонси, Уэльс": "Swansea, Wales",
  "Бернард Кенуэй": "Bernard Kenway",
  "Лайнетт Хопкинс": "Lynette Hopkins",
  //
  "Арно Дориан": "Arno Dorian",
  Француз: "Frenchman",
  "Королевство Франции": "Kingdom of France",
  Версаль: "Versailles",
  "Шарля Дориан": "Charles Dorian",
  Мари: "Marie",
  //
  "Шао Цзюнь": "Shao Jun",
  Китаянка: "Chinese",
  "Империя династии Мин": "Ming Empire",
  Пекин: "Beijing",
  Неизвестно: "Unknown",
  //
  "Иви и Джейкоб Фрай": "Evie and Jacob Fry",
  Великобритания: "Great Britain",
  Кроули: "Crowley",
  "Итан Фрай": "Ethan Fry",
  "Сесили Фрай": "Cecily Fry",
  //
  "Авелина де Гранпре": "Aveline de Grandpre",
  Француженка: "Frenchwoman",
  "Новая Франция": "New France",
  "Новый Орлеан, Луизиана,": "New Orleans, Louisiana,",
  " Филиппа Оливье де Грандпре": "Philippa Olivier de Grandpre",
  Жанна: "Jeanne",
  // Gameplay
  Геймплей: "Gameplay",
  "Основные игры серии Assassin's Creed, вышедшие до Assassin's Creed Odyssey, относятся к жанру action-adventure с элементами стелс-экшена. Assassin's Creed Odyssey и Valhalla позиционируются разработчиками как игры в жанре action RPG. Все основные игры имеют открытый мир, который представлен одной или несколькими локациями. Игровые локации в зависимости от части имеют разный масштаб и могут быть представлены как одним городом или небольшим участком сельской местности (например, в Assassin's Creed III представлены города Бостон и Нью-Йорк), так и целой страной (например, в Assassin's Creed Origins и Odyssey в уменьшенном масштабе представлены нынешние территории Египта и Греции соответственно).":
    "The main games of the Assassin's Creed series, released before Assassin's Creed Odyssey, belong to the action-adventure genre with elements of stealth action. Assassin's Creed Odyssey and Valhalla are positioned by the developers as action RPG games. All the main games have an open world, which is represented by one or game locations depending on the part have a different scale and can be represented as a single city or a small piece of countryside (for example, in Assassin's Creed III the cities of Boston and New York are represented), or an entire country (for example, in Assassin's Creed Origins and Odyssey are scaled-down representations of the current territories of Egypt and Greece, respectively).",
  "В зависимости от части в сюжетной линии в прошлом времени игрок может управлять одним или двумя протагонистами. В зависимости от игры функция выбора протагониста реализована различными способами: например, в Assassin's Creed III повествование от одного протагониста к другому переходит после прохождения нескольких заданий сюжетной кампании, в Syndicate игрок может свободно переключаться между 2 протагонистами, в Origins в нескольких заданиях основной сюжетной линии управление переключается на другого персонажа, а в Odyssey игрок может выбрать одного протагониста из двух представленных. Протагонисты сюжетных кампаний в прошлом, за исключением Альтаира ибн Ла-Ахада и Эцио Аудиторе да Фиренце, меняются в каждой части. В сюжетной линии в настоящем один и тот же герой обычно является протагонистом сразу нескольких частей. Например, Дезмонд Майлс выступает протагонистом первых 5 частей (начиная с Assassin's Creed и заканчивая Assassin's Creed III), а Лейла Хассан является главной героиней Assassin's Creed Origins, Odyssey и Valhalla.":
    "Depending on the part in the storyline in the past, the player can control one or two protagonists. Depending on the game, the protagonist selection function is implemented in various ways: for example, in Assassin's Creed III, the narrative switches from one protagonist to another after completing several tasks of the story campaign, in Syndicate, the player can freely switch between 2 protagonists, in Origins, control switches to another character in several tasks of the main storyline, and in Odyssey, the player can choose one protagonist from two presented. Ezio Auditore da Firenze, change in each part.In the storyline in the present, the same hero is usually the protagonist of several parts at once.For example, Desmond Miles is the protagonist of the first 5 parts (starting with Assassin's Creed and ending with Assassin's Creed III), and Layla Hassan is the main character of As sassin's Creed Origins, Odyssey and Valhalla.",
  "Одной из особенностей игр серии Assassin's Creed является использование искусства паркур для перемещения по игровому миру: игрок может «зацепиться» за любой выступ, забраться на любую постройку и т. д. Во всех играх серии есть «точки обзора» — здания или природные возвышенности, забравшись на которые, игрок может выполнить «синхронизацию» — открытие некоторой части карты (в играх до Assassin's Creed Origins) и точки быстрого перемещения (начиная с Assassin's Creed IV Black Flag). После выполнения «синхронизации» игрок может сделать «Прыжок веры» — выдуманный игровой прыжок, который позволяет осуществить быстрый спуск со здания или возвышенности в смягчающую падение среду (стог сена, водное пространство и т. д.). Также во многих играх серии присутствуют предметы коллекционирования и случайные события в открытом мире. Помимо передвижения пешком, игровой персонаж может использовать различные транспортные средства: лошадей, кареты, колесницы. В Assassin's Creed III, IV Black Flag, Rogue, Odyssey и в нескольких миссиях Origins игрок может использовать боевые корабли для перемещения и выполнения заданий. Во всех играх, кроме оригинальной Assassin's Creed, персонаж умеет плавать.":
    "One of the features of the games in the Assassin's Creed series is the use of parkour art to move around the game world: the player can «hook» on any ledge, climb any building, etc. All games in the series have «viewpoints» - buildings or natural hills , upon climbing which the player can «sync» - opening some part of the map (in games before Assassin's Creed Origins) and a fast travel point (starting with Assassin's Creed IV Black Flag). is a fictitious in-game jump that allows you to quickly descend from a building or hill into a fall-mitigating environment (haystack, body of water, etc.) Many games in the series also feature collectibles and random events in the open world. the game character can use various vehicles: horses, carriages, chariots.In Assassin's Creed III, IV Black Flag, Rogue, Odyssey and in several Origins missions, the player can use warships to navigate and complete missions. In all games except the original Assassin's Creed, the character can swim.",
  // Games
  "Перейти в Магазин": "Go to Shop",
  "Игры Серии": "Games of the Series",
  //
  "В 5 февраля 2008 году вышла игра Assassin's Creed ":
    "Assassin's Creed came out on February 5, 2008",
  "Игра относится к разряду проектов с открытым миром, то есть игроку дозволяется исследовать мир в свободном порядке. Всё игровое пространство представляет собой упрощённую модель Святой земли и поделено на 7 основных частей. Это три крупных города (Дамаск, Акра и Иерусалим), замок ассасинов (Масиаф) и пространство между ними (Королевство), разбитое на две части, а также цитадель Арсуф, локация возле Акры, которая открывается игроку в 6-м блоке памяти. Королевство представляет собой достаточно обширные площади между гор с небольшими поселениями местных жителей и лагерями крестоносцев. По территории королевства игрок волен передвигаться как пешком, так и на лошади. Почти все солдаты, которых он встречает, — враги Альтаира и Братства. Если привлекать к себе внимание, они могут узнать ассасина и попытаться убить. Масиаф — первое поселение, показываемое в игре. Оно построено на горе, и каждая следующая его улица располагается выше предыдущей. На самом пике стоит замок Братства, окружённый мощными стенами. В этой деревне игрок может приноровиться к городскому способу передвижения в игре — в стиле паркур, а также узнаёт основы расследования и выполнит своё первое после понижения в ранге задание — найти предателя среди жителей Масиафа.":
    "The game belongs to the category of open-world projects, that is, the player is allowed to explore the world in a free order. The entire game space is a simplified model of the Holy Land and is divided into 7 main parts. These are three large cities (Damascus, Acre and Jerusalem), the castle of the Assassins (Masyaf) and the space between them (Kingdom), divided into two parts, as well as the citadel of Arsuf, a location near Acre, which opens up to the player in memory block 6. The kingdom is a rather vast area between the mountains with small settlements of local residents and camps Crusaders. The player is free to move around the territory of the kingdom both on foot and on horseback. Almost all the soldiers he meets are enemies of Altair and the Brotherhood. If you draw attention to themselves, they can recognize the assassin and try to kill Masyaf - the first settlement shown in the game. It is built on a mountain, and each subsequent street is located higher than the previous one. At its peak stands the Brotherhood castle, surrounded by m solid walls. In this village, the player can adapt to the game's urban parkour-style movement, as well as learn the basics of investigation and complete their first task after being demoted - to find a traitor among the inhabitants of Masyaf.",
  //
  "В 5 марта 2010 году вышла игра Assassin's Creed II":
    "Assassin's Creed II was released on March 5, 2010",
  "После погружения в «Анимус» действие игры начинает разворачиваться в Италии, в Эпоху Возрождения, конец XV века. Главным героем игры становится семнадцатилетний юноша по имени Эцио, житель Флоренции. Отца Эцио, Джованни Аудиторе, предал его лучший друг Уберто Альберти, и в результате обвинения отец и братья Эцио — Федерико и Петруччо — были повешены. Для Эцио потеря семьи была сильной душевной травмой. Он убивает предателя своей семьи и скрывается вместе с матерью и сестрой у своего дяди Марио на вилле Аудиторе в Монтериджони.Позже Эцио узнаёт, что его семью предала семья Пацци, и он решает поквитаться с ней. Сперва он убивает младшего из этой семьи, Вьери Пацци. Через некоторое время после заговора против семьи Медичи Эцио убил отца Вьери, Франческо Пацци. а затем старшего из семьи предателей — Якопо Пацци — и его помощников (хотя, Эцио всего лишь нанёс Якопо последний удар). Из собрания тамплиеров, в котором непосредственно участвовал Якопо, Эцио узнаёт, что следующие действия тамплиеров будут в Венеции.":
    "After immersion in the Animus, the action of the game begins to unfold in Italy, in the Renaissance, at the end of the 15th century. The main character of the game becomes a seventeen-year-old boy named Ezio, a resident of Florence. Ezio's father, Giovanni Auditore, was betrayed by his best friend Uberto Alberti, and in as a result of the accusation, Ezio's father and brothers - Federico and Petruchio - were hanged. For Ezio, the loss of a family was a severe mental trauma. He kills a traitor to his family and hides with his mother and sister from his uncle Mario at the Auditore Villa in Monteriggioni. Later, Ezio learns that his family was betrayed by the Pazzi family, and he decides to get even with them.First, he kills the youngest of this family, Vieri Pazzi.Some time after the conspiracy against the Medici family, Ezio killed Vieri's father, Francesco Pazzi.and then the eldest of the family of traitors - Jacopo Pazzi - and his lieutenants (even though Ezio only delivered the final blow to Jacopo.) From a meeting of the Templars, in which Jacopo was directly involved, Ezio learns that the following actions of the Templar the priests will be in Venice.",
  // 
  "В 17 марта 2011 году вышла игра Assassin's Creed Brotherhood":"Assassin's Creed Brotherhood was released on March 17, 2011",
  "Игровой процесс стандартен для серии Assassin's Creed и является развитием игрового процесса Assassin's Creed II. Как и в предыдущих частях, основой механики игры является паркур, использование толпы и различных укрытий для незаметных убийств и развитой системы ближнего боя. Открытый мир игры представляет некоторую степень нелинейности прохождения, хотя основные сцены игры и её хронологические рамки выстроены с помощью системы скриптов. Непосредственное прохождение сюжетной линии занимает около 15 часов. Кроме того, к игрокам вернулась возможность переигрывать все сюжетные миссии игры.":"The gameplay is standard for the Assassin's Creed series and is an evolution of the Assassin's Creed II gameplay. As in previous installments, the game's mechanics are based on parkour, the use of crowds and various cover for stealth kills and an advanced melee system. The game's open world presents a certain degree of non-linearity passing through, although the main scenes of the game and its chronological framework are built using a script system.The direct passage of the storyline takes about 15 hours.In addition, the ability to replay all the storyline missions of the game returned to the players.",
  // 
  "В 15 ноября 2011 году вышла игра Assassin's Creed Revelations":"Assassin's Creed Revelations was released on November 15, 2011",
  "Сюжет игры начинается с того, что Дезмонд очнулся в первичной тестовой программе Анимуса, где уже находится 16-й (как выяснилось, его имя — Клэй Качмарек). 16-й объясняет ему, что Анимус пытается найти Дезмонда и удалить, как вредоносный вирус, а Клэй изо всех сил пытается предотвратить это. Дезмонд должен будет пережить последние воспоминания своих предков, и столкнуться со своим собственным прошлым, и если это ему удастся, то произойдёт синхронексус и он сможет выйти из комы.":"The plot of the game begins with Desmond waking up in the Animus' primary test program, where 16th is already (his name is revealed to be Clay Kaczmarek). 16th explains to him that the Animus is trying to find Desmond and remove it as a malicious virus and Clay tries his best to prevent it. Desmond will have to relive the last memories of his ancestors, and face his own past, and if he succeeds, then a synchronexus will occur and he will be able to wake up from a coma.",
  // 
  "21 ноября 2012 году вышла игра Assassin's Creed III":"Assassin's Creed III was released on November 21, 2012",
  "В Assasin’s Creed III, как и в прошлых частях серии, для перемещения по игровому миру игрок может использовать искусство паркур: можно «зацепиться» за любой выступ, забраться на любую постройку и т. д. В игре есть «точки обзора» — здания или природные возвышенности, забравшись на которые, игрок может выполнить «синхронизацию» — открытие некоторой части карты. После выполнения «синхронизации» игрок может сделать «Прыжок веры» — выдуманный игровой прыжок, который позволяет осуществить быстрый спуск со здания или возвышенности в смягчающую падение среду (стог сена, водное пространство и т. д.). Также в игре присутствуют предметы коллекционирования и случайные события в открытом мире. Помимо передвижения пешком, игровой персонаж может использовать транспортные средства: лошадей, а также боевой корабль для перемещения и выполнения заданий.":"In Assassin's Creed III, as in the previous parts of the series, the player can use the art of parkour to move around the game world: you can «hook »on any ledge, climb any building, etc. The game has «viewpoints» - buildings or natural hills, upon climbing which the player can perform a «sync »- opening up some part of the map. After doing a «sync», the player can make a «Leap of Faith» - a fictitious game jump that allows you to quickly descend from a building or hill into a fall-attenuating environment (haystack, body of water, etc.) There are also collectibles and random events in the open world. In addition to moving on foot, the player character can use vehicles: horses, as well as a warship to move around and complete tasks.",
  // 
  "В 21 ноября 2013 году вышла игра Assassin's Creed IV Black Flag":"Assassin's Creed IV Black Flag was released on November 21, 2013",
  "В Золотой век пиратства, Эдвард Кенуэй, участвует в заговоре между высокопоставленными тамплиерами в Британской и Испанской империях, которые, прикрываясь антипиратскими действиями в Карибском море, хотят найти Мудреца — позже оказавшегося Бартоломью Робертсом, который является единственным, кто может привести их к Обсерватории, устройству Первой Цивилизации, которое может следить за любым человеком в любой точке мира, когда ему предоставляют образец крови. Это они намерены использовать для шпионажа и шантажа мировых лидеров. Эдвард становится невольным участником событий, когда он убивает мошенника-ассасина Дункана Уолпола. Видя возможность получить прибыль, Эдвард занимает место Уолпола на встрече тамплиеров в Гаване, где он встречается с Вудсом Роджерсом, а также с губернатором Кубы и предводителем тамплиеров Лауреано Торресом. Его безрассудство ставит под угрозу весь Орден Ассасинов. Эдвард же вынужден преследовать Мудреца и заговорщиков с полуострова Юкатан до Ямайки. В конечном итоге, Эдвард настигает Робертса на острове Принсипи у африканского побережья.":"In the Golden Age of Piracy, Edward Kenway is involved in a conspiracy between high-ranking Templars in the British and Spanish empires who, under the guise of anti-piracy activities in the Caribbean, want to find the Sage - later revealed to be Bartholomew Roberts, who is the only one who can lead them to the Observatory, a First Civilization device that can spy on anyone anywhere in the world when provided with a blood sample, which they intend to use to spy on and blackmail world leaders.Edward becomes an unwitting participant in events when he kills rogue assassin Duncan Walpole. profit, Edward takes Walpole's place at a meeting of the Templars in Havana, where he meets with Woodes Rogers, as well as the governor of Cuba and the leader of the Templars, Laureano Torres. Jamaica.In the end Eventually, Edward overtakes Roberts on the island of Principe off the African coast.",
  // 
  "В 11 ноября 2014 году вышла игра Assassin's Creed Unity":"Assassin's Creed Unity was released on November 11, 2014",
  "Игра начинается с того, что молодой американский ассасин времён Семилетней войны Шэй Патрик Кормак преследует другого ассасина Лайама О’Брайена. Тренировочная попытка убить друга проваливается и ребята отправляются в лагерь своего старшего товарища Луи-Жозефа Готье Шевалье де ла Верендри. Шевалье, недовольный своенравием и наглостью Шэя, затевает с ним драку, но Лайам разнимает их. Ассасины отправляются на миссию по спасению попавших в плен к англичанам контрабандистов, с которыми должен был встретиться де ла Верендри. Попутно они захватывают корабль, который Кормак забирает себе и называет его «Морриган», и на нём отправляются спасать корабль Шевалье, «Кречет». Корабль возвращается к своему капитану, а Шэй и Лайам отправляются в штаб Братства.":"The game begins with a young American assassin from the Seven Years' War, Shay Patrick Cormac, pursuing another assassin, Liam O'Brien. A training attempt to kill a friend fails and the guys are sent to the camp of their older comrade Louis-Joseph Gauthier Chevalier de la Verendry. Chevalier, dissatisfied with waywardness and Shay's insolence, starts a fight with him, but Liam separates them.The Assassins go on a mission to rescue the smugglers who were captured by the British, whom de la Verendry was supposed to meet. Along the way, they seize the ship, which Cormac takes for himself and calls it «Morrigan», and on it they go to rescue the Chevalier's ship, the Gyrfalcon. The ship returns to its captain, and Shay and Liam go to the headquarters of the Brotherhood.",
  // 
  "В 10 марта 2015 году вышла игра Assassin's Creed Rogue":"Assassin's Creed Rogue was released on March 10, 2015",
  "В настоящие дни на игрока, играющего на распространяемой Абстерго консоли Helix и исследующего воспоминания о гибели ордена Тамплиеров в 1314 году, выходят ассасины и просят найти Мудреца в памяти, относящейся к годам Великой Французской революции. Сюжет разворачивается вокруг молодого ассасина Арно Виктора Дориана. Его отца убили, когда он был ещё маленьким. В тот же день он знакомится со своей будущей возлюбленной Элизой де ла Серр. Через много лет он становится свидетелем убийства её отца, Великого магистра ордена Тамплиеров Франсуа де ла Серра. В этом преступлении обвиняют его и сажают в Бастилию, где он знакомится с заключённым Пьером Беллеком, мастером ассасином. Когда они освобождаются, Беллек зовёт его в Братство. Поначалу Арно скептически относится к этой идее и сразу после побега отправляется к Элизе, но та обвиняет его в смерти отца, в надежде убедить Элизу в своей невиновности, он решает присоединиться к ассасинам (которых возглавляет граф Оноре де Мирабо), дабы найти убийц де ла Серра.":"In the present day, the player, playing on the Helix console distributed by Abstergo and exploring the memories of the death of the Knights Templar in 1314, is approached by the Assassins and asked to find the Sage in a memory dating back to the years of the French Revolution. The plot revolves around the young assassin Arno Victor Dorian. His father was killed when he was still young. On the same day he meets his future beloved Eliza de la Serre. Many years later, he witnesses the murder of her father, the Grand Master of the Knights Templar Francois de la Serre. He is accused of this crime and imprisoned to the Bastille, where he meets the imprisoned Pierre Bellec, a master assassin.When they are released, Bellec calls him to the Brotherhood.At first, Arno is skeptical about this idea and immediately after escaping goes to Eliza, but she blames him for the death of his father, in the hope of convincing Eliza in his innocence, he decides to join the Assassins (led by Count Honore de Mirabeau) in order to find the assassins. c de la Serra.",
  // 
  "В 19 ноября 2015 году  вышла игра Assassin's Creed Syndicate":"Assassin's Creed Syndicate was released on November 19, 2015",
  "В центре сюжета прошлого находятся ассасины-близнецы Джейкоб и Иви Фрай, которые прибывают в Лондон, чтобы освободить город от власти тамплиеров. Для этого Джейкоб основывает собственную уличную банду под названием «Грачи» и начинает борьбу с «Висельниками», бандой, контролируемой тамплиерами. В то же время Иви и глава ячейки ассасинов в Лондоне Генри Грин пытаются найти «Плащаницу Эдема», ещё один артефакт Предтеч, которую также хочет заполучить великий магистр Ордена тамплиеров Кроуфорд Старрик. По ходу игры главные герои встретят множество исторических личностей таких как: Чарльз Диккенс, Александр Грейам Белл, Чарльз Дарвин, Карл Маркс, Флоренс Найтингейл, Артур Конан Дойл, Бенджамин Дизраэли, Королева Виктория.":"At the center of the plot of the past are the twin assassins Jacob and Evie Fry, who arrive in London to free the city from the rule of the Templars. To do this, Jacob establishes his own street gang called the Rooks and begins to fight the Gallows, a gang controlled by the Templars At the same time, Evie and the head of the Assassin cell in London, Henry Green, are trying to find the Shroud of Eden, another Forerunner artifact that the Grand Master of the Knights Templar, Crawford Starrick, also wants to get his hands on.In the course of the game, the main characters will meet many historical figures such as: Charles Dickens, Alexander Graham Bell, Charles Darwin, Karl Marx, Florence Nightingale, Arthur Conan Doyle, Benjamin Disraeli, Queen Victoria.",
  // 
  "В 27 октября 2017 году вышла игра Assassin's Creed Origins":"Assassin's Creed Origins was released on October 27, 2017",
  "В 2017 году, Орден Тамплиеров, благодаря добытой два года назад Плащанице Эдема, готов воссоздать Предтечу, чтобы заполучить контроль над планетой. Вайолет да Коста оказалась членом Орудий Первой Воли и все это время помогала Юноне возродиться. Ассасины по словам Епископа планируют предпринять меры по возвращению Частицы Эдема.Игрок управляет египетской исследовательницей Лейлой Хассан (англ. Layla Hassan), которая исследует память последнего меджая — Байека из Сивы и его жены Айи из Александрии. Вместе они помогают Клеопатре в гражданской войне против её брата Птолемея XIII и закладывают основы Братства Ассасинов.":"In 2017, the Knights Templar, thanks to the Shroud of Eden obtained two years ago, is ready to recreate the Forerunner in order to gain control of the planet. Violet da Costa turned out to be a member of the Instruments of the First Will and all this time helped Juno be reborn. The Assassins, according to the Bishop, plan to take measures to The return of the Piece of Eden.The player controls Egyptian explorer Layla Hassan as she investigates the memory of the last Medjay, Bayek of Siwa and his wife Aya of Alexandria, together they assist Cleopatra in the civil war against her brother Ptolemy XIII and lay the foundations of the Brotherhood of Assassins.",
  // 
  "В 5 октября 2018 году вышла игра Assassin's Creed Odyssey":"Assassin's Creed Odyssey was released on October 5, 2018",
  "Главные герои — Алексиос и Кассандра, брат и сестра, являющиеся наёмниками (мистиями) и потомками спартанского царя Леонида. Они сражаются, используя клинок копья своего предка, который наделяет их в бою особыми способностями. Система развития персонажа представляет собой три древа способностей: ассасина, концентрирующегося на скрытности, воина с упором на боевые навыки и охотника, позволяющего лучше стрелять из лука. Доступны различные элементы снаряжения — нагрудники, пояса, шлемы, ботинки и наручи, которые можно комбинировать между собой и улучшать. Функцию орлиного зрения у главных героев подобно Байеку из Assassin's Creed Origins выполняет ручной орёл Икар. Уровень врагов теперь увеличивается вместе с уровнем персонажа. Вернулась шкала известности — при совершении преступлений на глазах у других она будет расти, и игрока могут объявить в розыск.":"The main characters are Alexios and Kassandra, brother and sister, who are mercenaries (mystia) and descendants of the Spartan king Leonidas. They fight using the spear blade of their ancestor, which gives them special abilities in battle. The character development system consists of three skill trees: assassin a warrior with a focus on stealth, a warrior with a focus on combat skills, and a hunter for better archery.A variety of equipment items are available - chests, belts, helmets, boots and bracers, which can be combined with each other and improved. Bayek from Assassin's Creed Origins is wielded by Icarus, the pet eagle. Enemies now level up with character level. The notoriety bar has returned - when committing crimes in front of others, it will increase, and the player may be put on the wanted list.",
  // 
  "В 10 ноября 2020 году вышла игра Assassin's Creed Valhalla":"Assassin's Creed Valhalla came out November 10, 2020",
  "Действие игры начинается в 873 году во времена завоеваний викингов. Игроку предстоит взять на себя роль викинга Эйвор, ведущего своих сородичей от берегов холодной Норвегии до плодородных земель Англии в поисках нового дома. Клану Эйвор противостоят лидеры четырёх англо-саксонских королевств: Уэссекса, Нортумбрии, Восточной Англии и Мерсии во главе с Альфредом Великим. Также Эйвор предстоит встретиться с Незримыми и помочь им в борьбе против Ордена древних[комм. 1]. Как и в предыдущей части серии в XXI веке продолжается история Лейлы Хассан[3]. Помимо Англии и Норвегии действие игры также происходит на территории Северной Америки, под названием Винланд и в фантастических мирах: Асгарде, Йотунхейме и Вальхалле.":"The action of the game begins in 873 during the Viking conquests. The player will take on the role of the Viking Eivor, leading his relatives from the shores of cold Norway to the fertile lands of England in search of a new home. The Eivor clan is opposed by the leaders of four Anglo-Saxon kingdoms: Wessex, Northumbria , East Anglia and Mercia, led by Alfred the Great.Eivor will also meet with the Invisibles and help them in the fight against the Order of the Ancients [comm. 1]. As in the previous part of the series, the story of Layla Hassan continues in the 21st century[3]. and Norway, the game also takes place in North America called Vinland and in fantasy worlds: Asgard, Jotunheim and Valhalla.",
  // Main
  "11 января 1165 года":"January 11, 1165",
  "24 июня 1459 года" :"June 24, 1459",
  "4 апреля 1756":"April 4, 1756",
  "10 марта 1693 г.":"March 10, 1693",
  "26 августа 1768 г.":"August 26, 1768",
  "7 ноября 1505 г.":"November 7, 1505",
  "9 ноября 1847 г.":"November 9, 1847",
  "20 июня 1747 г.":"June 20, 1747",
  // SHOP
  "Добавить":"Add",
  "Обшая цена:":"Total price:",
  "Удалить из корзины":"Remove from Cart",
  // HEADER
  "Игры":"Games",
  "Персонажы":"Persons",
  "Корзина":"Cart",
  "Войти":"Log In",
  "Регистр":"Registr",
  // MODAL
  "Фамилия":"LastName",
  "Е-Мейл":"E-Mail",
  "Имя":"FirstName",
  "Пароль":"Password",
  "Отправить":"Submit",
  "Запомнить Меня":"Remember Me",
  "Вход":"Log In",
  "Отмена":"Cancel",
};

export default translationsEn;
